export const Errors = {
    // math
    MATH_MULTIPLICATION_OVERFLOW: '1',
    MATH_ADDITION_OVERFLOW: '2',
    MATH_DIVISION_BY_ZERO: '3',

    // settings/acl
    // ACL_ONLY_ADDRESS_ADMIN_CAN_CALL: '4',
    ACL_ONLY_GOVERNANCE_CAN_CALL: '4',
    ACL_ONLY_EMERGENCY_ADMIN_CAN_CALL: '5',
    ACL_ONLY_POOL_ADMIN_CAN_CALL: '6',
    ACL_ONLY_LIQUIDATOR_CAN_CALL: '7',
    ACL_ONLY_LIQUIDATION_OPERATOR_CAN_CALL: '8',
    ACL_ONLY_AIRDROP_OPERATOR_CAN_CALL: '9',
    ACL_ONLY_POOL_CAN_CALL: '10',

    //deposit
    DEPOSIT_AMOUNT_SHOULD_BE_BIGGER_THAN_ZERO: '11',

    // withdraw
    WITHDRAW_AMOUNT_NOT_ALLOWED: '12',
    WITHDRAW_LIQUIDITY_NOT_SUFFIENCE: '13',

    // borrow
    BORROW_DURATION_NOT_ALLOWED: '14',
    BORROW_AMOUNT_EXCEED_BORROW_LIMIT: '15',

    // repay
    REPAY_STATUS_ERROR: '16',
    REPAY_AMOUNT_NOT_ENOUGH: '17',

    // extend
    EXTEND_STATUS_ERROR: '18',
    EXTEND_MSG_VALUE_ERROR: '19',

    // liquidate
    START_LIQUIDATION_STATUS_ERROR: '20',
    END_LIQUIDATION_STATUS_ERROR: '21',
    END_LIQUIDATION_AMOUNT_ERROR: '22',

    // loan
    LOAN_SET_STATUS_ERROR: '23',
    LOAN_REPAYER_IS_NOT_OWNER: '24',
    LOAN_LIQUIDATING_STATUS_CAN_NOT_BE_UPDATED: '25',
    LOAN_CALLER_IS_NOT_OWNER: '26',
    LOAN_IS_END: '27',
    FLASHLOAN_EXECUTOR_ERROR: '28',
    FLASHLOAN_STATUS_ERROR: '29',

    // money market
    MONEY_MARKET_DEPOSIT_AMOUNT_ALLOWED: '30',
    MONEY_MARKET_WITHDRAW_AMOUNT_NOT_ALLOWED: '31',
    MONEY_MARKET_APPROVAL_FAILED: '32',
    MONEY_MARKET_DELEGATE_CALL_ERROR: '33',

    // price oracle
    PRICE_ORACLE_ROUND_INTERVAL_CAN_NOT_BE_0: '34',
    PRICE_ORACLE_HAS_NO_PRICE_FEED: '35',
    PRICE_ORACLE_INCORRECT_TIMESTAMP: '36',
    PRICE_ORACLE_PARAMS_ERROR: '37',

    // reserve
    RESERVE_LIQUIDITY_INSUFFICIENT: '38',
    RESERVE_DOES_NOT_EXISTS: '39',
    RESERVE_INDEX_OVERFLOW: '40',

    // token
    AMOUNT_SCALED_IS_ZERO: '41',
    AMOUNT_TRANSFER_OWERFLOW: '42',

    ETH_TRANSFER_FAILED: '43',
    RECEIVE_NOT_ALLOWED: '44',
    FALLBACK_NOT_ALLOWED: '45',
};
