export const Errors = {
    // math
    MATH_MULTIPLICATION_OVERFLOW: '1',
    MATH_ADDITION_OVERFLOW: '2',
    MATH_DIVISION_BY_ZERO: '3',

    // settings/acl
    ACL_ONLY_ADDRESS_ADMIN_CAN_CALL: '4',
    ACL_ONLY_GOVERNANCE_CAN_CALL: '5',
    ACL_ONLY_EMERGENCY_ADMIN_CAN_CALL: '6',
    ACL_ONLY_POOL_ADMIN_CAN_CALL: '7',
    ACL_ONLY_LIQUIDATOR_CAN_CALL: '8',
    ACL_ONLY_LIQUIDATION_OPERATOR_CAN_CALL: '9',
    ACL_ONLY_AIRDROP_OPERATOR_CAN_CALL: '10',
    ACL_ONLY_POOL_CAN_CALL: '11',

    //deposit
    DEPOSIT_AMOUNT_SHOULD_BE_BIGGER_THAN_ZERO: '12',

    // withdraw
    WITHDRAW_AMOUNT_NOT_ALLOWED: '13',
    WITHDRAW_LIQUIDITY_NOT_SUFFIENCE: '14',

    // borrow
    BORROW_DURATION_NOT_ALLOWED: '15',
    BORROW_AMOUNT_EXCEED_BORROW_LIMIT: '16',

    // repay
    REPAY_STATUS_ERROR: '17',
    REPAY_AMOUNT_NOT_ENOUGH: '18',

    // extend
    EXTEND_STATUS_ERROR: '19',
    EXTEND_MSG_VALUE_ERROR: '20',

    // liquidate
    START_LIQUIDATION_STATUS_ERROR: '21',
    END_LIQUIDATION_STATUS_ERROR: '22',
    END_LIQUIDATION_AMOUNT_ERROR: '23',

    // loan
    LOAN_SET_STATUS_ERROR: '24',
    LOAN_REPAYER_IS_NOT_OWNER: '25',
    LOAN_LIQUIDATING_STATUS_CAN_NOT_BE_UPDATED: '26',
    LOAN_CALLER_IS_NOT_OWNER: '27',
    LOAN_IS_END: '28',
    FLASHLOAN_EXECUTOR_ERROR: '29',
    FLASHLOAN_STATUS_ERROR: '30',

    // money market
    MONEY_MARKET_DEPOSIT_AMOUNT_ALLOWED: '31',
    MONEY_MARKET_WITHDRAW_AMOUNT_NOT_ALLOWED: '32',
    MONEY_MARKET_APPROVAL_FAILED: '33',
    MONEY_MARKET_DELEGATE_CALL_ERROR: '34',

    // price oracle
    PRICE_ORACLE_ROUND_INTERVAL_CAN_NOT_BE_0: '35',
    PRICE_ORACLE_HAS_NO_PRICE_FEED: '36',
    PRICE_ORACLE_INCORRECT_TIMESTAMP: '37',
    PRICE_ORACLE_PARAMS_ERROR: '38',

    // reserve
    RESERVE_LIQUIDITY_INSUFFICIENT: '39',
    RESERVE_DOES_NOT_EXISTS: '40',
    RESERVE_INDEX_OVERFLOW: '41',

    // token
    AMOUNT_SCALED_IS_ZERO: '42',
    AMOUNT_TRANSFER_OWERFLOW: '43',

    ETH_TRANSFER_FAILED: '44',
    RECEIVE_NOT_ALLOWED: '45',
    FALLBACK_NOT_ALLOWED: '46',
};
